<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-06T14:35:58 IST" name="Suite" finished-at="2024-11-06T14:36:41 IST" duration-ms="42436">
    <groups>
      <group name="Purchase">
        <method signature="SubmitTest.submitOrder(java.util.HashMap)[pri:0, instance:department.tests.SubmitTest@4fb61f4a]" name="submitOrder" class="department.tests.SubmitTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-11-06T14:35:58 IST" name="Submit order test" finished-at="2024-11-06T14:36:41 IST" duration-ms="42436">
      <class name="department.tests.SubmitTest">
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:department.tests.SubmitTest@4fb61f4a]" started-at="2024-11-06T14:35:58 IST" name="LaunchApplication" finished-at="2024-11-06T14:36:03 IST" duration-ms="5223" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:department.tests.SubmitTest@4fb61f4a]" started-at="2024-11-06T14:36:03 IST" name="submitOrder" data-provider="getdata" finished-at="2024-11-06T14:36:19 IST" duration-ms="15279" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Test@1234, email=prasanth@gmail.com, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="endOperation()[pri:0, instance:department.tests.SubmitTest@4fb61f4a]" started-at="2024-11-06T14:36:19 IST" name="endOperation" finished-at="2024-11-06T14:36:19 IST" duration-ms="184" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endOperation -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:department.tests.SubmitTest@4fb61f4a]" started-at="2024-11-06T14:36:19 IST" name="LaunchApplication" finished-at="2024-11-06T14:36:22 IST" duration-ms="2817" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:department.tests.SubmitTest@4fb61f4a]" started-at="2024-11-06T14:36:22 IST" name="submitOrder" data-provider="getdata" finished-at="2024-11-06T14:36:37 IST" duration-ms="15729" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Test@123456, email=prasanthb@gmail.com, productName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="endOperation()[pri:0, instance:department.tests.SubmitTest@4fb61f4a]" started-at="2024-11-06T14:36:37 IST" name="endOperation" finished-at="2024-11-06T14:36:38 IST" duration-ms="247" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endOperation -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:department.tests.SubmitTest@4fb61f4a]" started-at="2024-11-06T14:36:38 IST" name="LaunchApplication" finished-at="2024-11-06T14:36:40 IST" duration-ms="1868" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="orderHistoryTest()[pri:0, instance:department.tests.SubmitTest@4fb61f4a]" started-at="2024-11-06T14:36:40 IST" name="orderHistoryTest" finished-at="2024-11-06T14:36:40 IST" depends-on-methods="department.tests.SubmitTest.submitOrder" duration-ms="709" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at department.tests.SubmitTest.orderHistoryTest(SubmitTest.java:55)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
        <test-method is-config="true" signature="endOperation()[pri:0, instance:department.tests.SubmitTest@4fb61f4a]" started-at="2024-11-06T14:36:40 IST" name="endOperation" finished-at="2024-11-06T14:36:41 IST" duration-ms="189" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endOperation -->
      </class> <!-- department.tests.SubmitTest -->
    </test> <!-- Submit order test -->
  </suite> <!-- Suite -->
</testng-results>
